# kubernetes cluster installator ansible roles
# Copyright (C) 2017  Manuel Bovo

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- name: "Check for swap devices"
  shell: swapon -s | grep -q dev
  register: is_swap
  changed_when: "is_swap.rc == 0"
  failed_when: "is_swap.rc > 1"

- name: "Disabling swap"
  command: "swapoff -a"
  when: not ansible_connection == "docker" and is_swap.rc == 0

- name: "Setting swappiness to 0"
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
    reload: yes
  when: is_swap.rc == 0

- name: "Remove swap from fstab"
  lineinfile:
    path: "/etc/fstab"
    regexp: "^/dev.*swap"
    state: absent
    backup: yes
  when: is_swap.rc == 0