# kubernetes cluster installator ansible roles
# Copyright (C) 2017  Manuel Bovo

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- name: "Check for swap devices"
  shell: swapon -s | grep -q dev
  register: is_swap
  changed_when: "is_swap.rc == 0"
  failed_when: "is_swap.rc > 1"

- name: "Disabling swap"
  command: "swapoff -a"
  when: not ansible_connection == "docker" and is_swap.rc == 0

- name: "Setting swappiness to 0"
  lineinfile:
    path: "/etc/sysctl.conf"
    line: "vm.swappiness = 0"
    create: yes
    state: present
  when: is_swap.rc == 0

- name: "Load kernel modules"
  command: "modprobe {{item}}"
  with_items:
    - br_netfilter
  when: new_packages.changed

- name: "Reload sysctl"
  command: "sysctl -p"
  when: new_packages.changed

- stat:
    path: "/etc/fstab.bak"
  register: fstab_backup

- name: "Backup copy of fstab"
  copy:
    src: "/etc/fstab"
    dest: "/etc/fstab.bak"
    remote_src: True
  when: fstab_backup.stat and not fstab_backup.stat.exists

- name: "Remove swap from fstab"
  lineinfile:
    path: "/etc/fstab"
    regexp: "^/dev.*swap"
    state: absent
  when: is_swap.rc == 0