# kubernetes cluster installator ansible roles
# Copyright (C) 2017  Manuel Bovo

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---

- name: "Local tmp directory"
  file:
    dest: "{{local_tmp_path}}"
    state: directory
  delegate_to: localhost
  become: false
  run_once: True

- name: "Generate Etcd CA certs+key"
  shell: kubeadm init phase certs etcd-ca
  run_once: True
  when: "not '/etc/kubernetes/pki/etcd/ca.crt' is exists"

- name: "Copy CA Certs locally"
  fetch:
    src: "{{item}}"
    dest: "{{local_tmp_path}}/"
    flat: True
  with_items:
    - "/etc/kubernetes/pki/etcd/ca.crt"
    - "/etc/kubernetes/pki/etcd/ca.key"
  run_once: True  

- name: "Remote tmp directory"
  file:
    dest: "{{etcd_tmp_path}}"
    state: directory

- name: Template etcd config"
  template:
    src: kubeadmcfg.yaml.j2
    dest: "{{etcd_tmp_path}}/kubeadmcfg.yaml"
    mode: u+rwx

- name: "PKI directory"
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory

- name: Upload CA certs 
  copy:
    src: "{{local_tmp_path}}/{{item}}"
    dest: "/etc/kubernetes/pki/etcd/"
  with_items:
    - "ca.key"
    - "ca.crt"

- name: "Create server cert"
  shell: kubeadm init phase certs etcd-server --config={{etcd_tmp_path}}/kubeadmcfg.yaml

- name: "Create peer cert"
  shell: kubeadm init phase certs etcd-peer --config={{etcd_tmp_path}}/kubeadmcfg.yaml

- name: "Create healtcheck cert"
  shell: kubeadm init phase certs etcd-healthcheck-client --config={{etcd_tmp_path}}/kubeadmcfg.yaml

- name: "Create client cert for apiserver"
  shell: kubeadm init phase certs apiserver-etcd-client --config={{etcd_tmp_path}}/kubeadmcfg.yaml

#- name: "Generate static manifests files"
#  shell: kubeadm init phase etcd local --config={{etcd_tmp_path}}/kubeadmcfg.yaml

- name: Install etcd via package manager
  package:
    name: etcd
    state: present

- name: Write etcd config file
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    group: etcd
    owner: etcd
    mode: 064

- name: Make sure database directory /var/lib/etcd exists and has proper permissions
  file:
    path: /var/lib/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: 0755

- name: "Set proper permission to pki folder"
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    owner: etcd
    group: etcd
    recurse: yes

- name: Enable and start etcd
  service:
    name: etcd
    state: started

