# kubernetes cluster installator ansible roles
# Copyright (C) 2017  Manuel Bovo

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---

# - name: "Update local timezone"
#   block:
#     - name: "Remove old timezone"
#       file: 
#         path: /etc/localtime
#         state: absent
- name: "Force timezone"
  file:
    src: /usr/share/zoneinfo/{{timezone}}
    dest: /etc/localtime
    state: link

- name: "Install docker repo"
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 

- name: "Install docker"
  yum:
    name: docker-{{CRI_VERSION}}
    state: present
    update_cache: true

- name: "Create docker settings dir"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - /etc/systemd/system/docker.service.d
    - /etc/docker

- name: "Configure docker"
  blockinfile:
    path: /etc/docker/daemon.json
    create: true
    marker: ""
    block: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
          "overlay2.override_kernel_check=true"
        ]
      }

- name: "Re-apply systemd"
  systemd:
    daemon_reload: yes

- name: "Restart and enable docker daemon"
  systemd:
    name: docker
    state: started
    enabled: true

- name: "Add kernel options"
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items: "{{ docker_kernel_options }}"

- name: "Create docker client configuration"
  file:
    path: "/root/.docker/"
    state: directory

- name: "Installing config.json for user root"
  template:
    src: "config.json.j2"
    dest: "/root/.docker/config.json"

- name: "Ensure target directory exists"
  file:
    dest: "/var/lib/kubelet"
    state: directory
    recurse: True

- name: "Copying docker config.json"
  copy:
    remote_src: True
    src: "/root/.docker/config.json"
    dest: "/var/lib/kubelet/config.json"