---
# tasks file for master

- name: Templating kubeadm config
  template:
    src: kubeadmcfg.yaml.j2
    dest: /etc/kubernetes/kubeadmcfg.yaml

- name: "Enable kubelet"
  service:
    name: "kubelet"
    enabled: yes

- name: "Creating CA certs"
  shell: kubeadm init phase certs ca --config /etc/kubernetes/kubeadmcfg.yaml
  run_once: True
  when: inventory_hostname in groups['masters'][0]

- name: "Retrieve CA certs"
  fetch:
    src: "{{item}}"
    dest: "{{local_tmp_path}}/"
    flat: True
  with_items:
    - "/etc/kubernetes/pki/ca.crt"
    - "/etc/kubernetes/pki/ca.key"
  run_once: True  
  when: inventory_hostname in groups['masters'][0]

- name: "PKI directory"
  file:
    path: /etc/kubernetes/pki
    state: directory

- name: Upload CA certs 
  copy:
    src: "{{local_tmp_path}}/{{item}}"
    dest: "/etc/kubernetes/pki/"
  with_items:
    - "ca.key"
    - "ca.crt"

- name: "Init the cluster"
  shell: kubeadm init --config /etc/kubernetes/kubeadmcfg.yaml --upload-certs