#
# Playbook to set up a Kubernetes cluster.
#
--- 

- name: "LoadBalancer"
  hosts: lb
  roles:
    - {role: nginx}
  tags:
    - lb

- name: "Etcd"
  hosts: etcd
  roles:
    - {role: prepare, tags: etcd_prepare}
    - {role: etcd,    tags: etcd_install}
  tags:
    - etcd

- name: "Kubernetes Control Plane"
  hosts: masters
  roles:
    - {role: prepare,    tags: masters_prepare}
    - {role: cri    ,    tags: masters_cri }
    - {role: master ,    tags: masters_install}
    - {role: add-labels, tags: masters_label}
  tags:
    - masters

- name: "Kubernetes Workers"
  hosts: workers
  roles:
    - {role: prepare,    tags: workers_prepare}
    - {role: cri    ,    tags: workers_cri}
    - {role: worker ,    tags: workers_install}
    - {role: add-labels, tags: workers_label }
  tags:
    - workers

- name: "Remove Nodes"
  hosts: workers
  roles:
    - {role: reset, when: "toRemove|default('false')|bool" }
  tags:
    - remove